from fastapi import APIRouter
from pydantic import BaseModel
import asyncio
from agents import search_agent, linguistic_agent, triplet_agent, judge_agent

router = APIRouter()

class AnalyzeRequest(BaseModel):
    claim: str

@router.post("/analyze")
async def analyze_claim(request: AnalyzeRequest):
    claim = request.claim
    
    # 1. Search Agent (DuckDuckGo Live)
    search_results = await search_agent.fetch_news_context(claim)
    
    # 2. Linguistic Agent (Keeping mock or simple logic for now as requested)
    # We will pass the claim to the triplet extractor
    
    # 3. Triplet Agent (Gemini live extraction)
    # Give the context of the search results as text to extract better triplets from reality
    context_text = f"Claim: {claim}\n" + "\n".join([e["quote"] for e in search_results])
    triplets = await triplet_agent.extract_triplets(context_text)
    
    # 4. Judge Agent (Gemini 1.5 Pro live reasoning)
    verdict_data = await judge_agent.generate_verdict(claim, search_results, triplets)
    
    # Provide temporal timeline mock (Or can be generated by AI, keeping simple for demo)
    timeline = [
        {"time": "30 days ago", "text": "Historical events matching the extracted entities."},
        {"time": "7 days ago", "text": "Initial reports from trusted sources surfaced."},
        {"time": "Live", "text": "DuckDuckGo scraped latest indexed news for cross-reference."}
    ]

    return {
        "verdict": verdict_data.get("verdict", "Uncertain"),
        "confidence": verdict_data.get("confidence", 50),
        "triplets": triplets,
        "timeline": timeline,
        "evidence": search_results,
        "sentence_analysis": verdict_data.get("sentence_analysis", [
            {
                "text": claim,
                "label": "UNCERTAIN",
                "confidence": 50,
                "reason": "Fallback parsing applied."
            }
        ])
    }
